language: python
python:
  - "2.7"
  - "3.5"
sudo: false
env:
  - TOXENV=py27-dj17
  - TOXENV=py27-dj18
  - TOXENV=py27-dj19
  - TOXENV=py27-dj110
  - TOXENV=py27-dj111
  - TOXENV=py35-dj18
  - TOXENV=py35-dj19
  - TOXENV=py35-dj110
  - TOXENV=py35-dj111
  - TOXENV=py35-djdev
matrix:
  allow_failures:
    - env: TOXENV=py35-djdev
install:
  - pip install tox
script: tox
